### ISSUE TITLE
Opening sr adds another SimpleR Extension menu every time!

### ISSUE THREAD

**Issue by DOSull** [NetLogo/SimpleR-Extension#6]
_Every time_ I open a model that invokes `extensions [sr]` it adds an additional SimpleR Extensions menu to the top bar.

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/e2be0e0b-ced5-453b-b75e-2d030d8dbfdd">

The gap in the menubar is the Mac's 'notch' for the camera.

The only line of code in the model shown is `extensions [sr]` - it seems to be triggered by loading the model - so even just doing File - Recent Files > and selecting the already open model again to relaunch it causes this behaviour, no execution of any `sr` reporters or procedures is necessary.

This is on Apple M2 Silicon MacOS Sonoma 14.5.

**Comment by LaCuneta** [comment]
This issue did not occur for me on Ubuntu 22.  I am fortunately able to reproduce this issue on an older, non-Apple-Silicon MacBook.  I'll update once a fix is in place.

**Comment by DOSull** [comment]
Certainly seems likely to be an OS / GUI components related issue, so can understand it not happening on another OS. Good to know a fix is on the to do list!

**Comment by LaCuneta** [comment]
After some research, the problem lies somewhere in the main NetLogo code and affects extensions beyond just SimpleR, so it's more work than I'm able to handle at the moment.  I've gone ahead and [opened an issue there](https://github.com/NetLogo/NetLogo/issues/2295) that references this.  I'm going to close this one for now, but you should be able to subscribe to the issue there to get updates on it.

**Comment by DOSull** [comment]
Sounds good - have subscribed over there!
